# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JustAskBizz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JustAskBizz
pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'
end
